/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuestRouteImport } from './routes/quest'
import { Route as PakarRouteImport } from './routes/pakar'
import { Route as ChroniclesRouteImport } from './routes/chronicles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const QuestRoute = QuestRouteImport.update({
  id: '/quest',
  path: '/quest',
  getParentRoute: () => rootRouteImport,
} as any)
const PakarRoute = PakarRouteImport.update({
  id: '/pakar',
  path: '/pakar',
  getParentRoute: () => rootRouteImport,
} as any)
const ChroniclesRoute = ChroniclesRouteImport.update({
  id: '/chronicles',
  path: '/chronicles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chronicles': typeof ChroniclesRoute
  '/pakar': typeof PakarRoute
  '/quest': typeof QuestRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chronicles': typeof ChroniclesRoute
  '/pakar': typeof PakarRoute
  '/quest': typeof QuestRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chronicles': typeof ChroniclesRoute
  '/pakar': typeof PakarRoute
  '/quest': typeof QuestRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chronicles' | '/pakar' | '/quest' | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chronicles' | '/pakar' | '/quest' | '/api/chat'
  id: '__root__' | '/' | '/chronicles' | '/pakar' | '/quest' | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChroniclesRoute: typeof ChroniclesRoute
  PakarRoute: typeof PakarRoute
  QuestRoute: typeof QuestRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quest': {
      id: '/quest'
      path: '/quest'
      fullPath: '/quest'
      preLoaderRoute: typeof QuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pakar': {
      id: '/pakar'
      path: '/pakar'
      fullPath: '/pakar'
      preLoaderRoute: typeof PakarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronicles': {
      id: '/chronicles'
      path: '/chronicles'
      fullPath: '/chronicles'
      preLoaderRoute: typeof ChroniclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChroniclesRoute: ChroniclesRoute,
  PakarRoute: PakarRoute,
  QuestRoute: QuestRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
